### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by orbea** [juur/tmpfilesd#7]
Not sure why I didn't notice this earlier, but when these directories do not exist there are invalid uses of `free()`.
```
# tmpfilesd --create --remove --boot --exclude-prefix=/dev 
tmpfilesd: process_folder: opendir: </etc/tmpfiles.d>: No such file or directory
free(): invalid pointer
The process was killed by SIGABRT: Aborted
```
This seems to be from `main.c`.
https://github.com/juur/tmpfilesd/blob/6073d17ce856ac9c0dbbcb0bcc1e3cd3836b6609/src/main.c#L2135-L2149

What should be installed in `/etc/tmpfiles.d`? On my system the installed package contains:
```
 * Contents of sys-apps/tmpfilesd-9999:
/bin
/bin/tmpfilesd
/etc
/etc/conf.d
/etc/conf.d/tmpfilesd-dev
/etc/conf.d/tmpfilesd-setup
/etc/cron.daily
/etc/cron.daily/tmpfilesd-clean
/etc/init.d
/etc/init.d/tmpfilesd-dev
/etc/init.d/tmpfilesd-setup
/usr
/usr/lib
/usr/lib/tmpfiles.d
/usr/lib/tmpfiles.d/tmp.conf
/usr/lib/tmpfiles.d/var.conf
/usr/share
/usr/share/doc
/usr/share/doc/tmpfilesd-9999
/usr/share/doc/tmpfilesd-9999/README.md.gz
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/tmpfilesd.8.gz
```
I am not seeing config files installed in `/etc/tmpfiles.d/`, should it be changed to `/lib/tmpfiles.d`?
https://github.com/juur/tmpfilesd/blob/6073d17ce856ac9c0dbbcb0bcc1e3cd3836b6609/Makefile.in#L74

**Comment by juur** [comment]
According to the man page on my system for tmpfiles.d:

SYNOPSIS
       /etc/tmpfiles.d/*.conf
       /run/tmpfiles.d/*.conf
       /usr/lib/tmpfiles.d/*.conf

Additionally the systemd RPM contains /etc/tmpfiles.d

**Comment by juur** [comment]
Thanks, the issue was assign "" to opt_root if no opt_root was supplied so it attempt to free() the anonymous variable (or whatever they're called in C) ""
