### ISSUE TITLE
mknod fails to create directories

### ISSUE THREAD

**Issue by orbea** [juur/tmpfilesd#8]
On my system when starting tmpfilesd I receive this output.
```
 * Create Static Devices Nodes in /dev ...
tmpfilesd: CREATE_CHAR/BLK: mknod(/dev/net/tun): No such file or directory
tmpfilesd: CREATE_CHAR/BLK: mknod(/dev/snd/timer): No such file or directory
tmpfilesd: CREATE_CHAR/BLK: mknod(/dev/snd/seq): No such file or directory
```
The init command is:
```
tmpfilesd --prefix=/dev --create --boot
```
Where the init script which is basically a copy of the systemd version is:
```
#!/sbin/openrc-run
# Copyright 2023 Gentoo Authors
# Released under the MIT license.

description="Create Static Devices Nodes in /dev"

depend()
{
	provide tmpfiles-dev tmpfiles.dev
	use dev-mount
	before dev
	keyword -prefix -vserver
}

start()
{
	ebegin "${description}"
	tmpfilesd --prefix=/dev --create --boot
	eend $?
}
```
It seems to me its not capable of creating directories recursively? For example if I manually rerun the command the `/dev/snd/` directory now exists so `/dev/net/seq` gets created while `/dev/net/` does not exist so I still recieve the `/dev/net/tun` error.

**Comment by orbea** [comment]
@juur Any help would be appreciated.

**Comment by juur** [comment]
looks like systemd changed behaviour from when i started this project https://github.com/poettering/systemd/commit/bd5e6255b0f61fa768e8f3b27a23845471874c1e i'll have a look sometime.

**Comment by juur** [comment]
> @juur Any help would be appreciated.

i've pushed a fix, let me know if it works.

**Comment by orbea** [comment]
@juur Yes, as of commit https://github.com/juur/tmpfilesd/commit/e3b08a70515586f258ac3be5f4614447912edbee it works, thanks!
